steps:
  - name: Install deps
    plugin: Shell
    command: 'npm install -g stylelint ; npm install stylelint-config-standard'
  - name: Lint CSS
    plugin: Shell
    command: 'stylelint style.css'
