steps:
  - name: Update NodeJS and npm
    command: 'sudo npm cache clean -f ; sudo npm install -g n ; sudo n 5.6.0 ; sudo ln -sf /usr/local/n/versions/node/5.6.0/bin/node /usr/bin/node'
  - name: Install deps
    command: 'cd $SRC_DIR && npm install'
  - name: Lint CSS
    command: 'cd $SRC_DIR && ./node_modules/.bin/stylelint "./css/*.css" --color'
  - name: Lint JS
    command: 'cd $SRC_DIR && ./node_modules/.bin/eslint js --color'
